"""REFEREE turn 667, part 4: the full rotational-symmetry classification.

Setup.  A finite group of affine maps preserving an arrangement has a common
fixed point and is conjugate to a subgroup of O(2): cyclic or dihedral.  This
file settles the CYCLIC case generated by a rotation of order m >= 2 (m = 2 is
the point reflection -I, T664's family).  Mirror/dihedral symmetry is a
DIFFERENT family and nothing here touches it.

Lemma 1 (fixed lines).  For m >= 3 the linear part L has minimal polynomial the
  m-th cyclotomic factor with complex roots, so no real eigenvector, so g fixes
  no line.  For m = 2, L = -I and the fixed lines are exactly the lines through
  the centre.  For even m >= 4, L^(m/2) = -I, so the point reflection is in the
  group.
Lemma 2 (line orbits).  m odd => every line orbit has size m, so m | k.
  m even => orbits have size m, or m/2 for lines through the centre.
Lemma 3 (triangle stabilisers).  No triangular face is fixed by the point
  reflection (T664: a fixed triple needs a fixed line plus a swapped pair, and
  a swapped pair is parallel).  A 3-set invariant under a rotation of order
  s >= 4 would be a union of line orbits of size >= 4.  So a triangle's
  stabiliser has order 1 or 3, and
        3 nmid m  =>  T = 0 (mod m)        3 | m, m > 3  =>  T = 0 (mod m/3)
        m = 3     =>  T = b (mod 3), b the number of full-orbit triangles.
Lemma 4 (segment budget under the point reflection).  With f lines through the
  centre, the other k-f fall into (k-f)/2 parallel pairs.  Bounded edges
  B = sum_i (r_i - 1) with r_i the distinct crossings on line i:
      paired line   r_i <= k-2      centre line   r_i <= 1 + (k-f)
      B <= (k-f)(k-3) + f(k-f)
  and 3T <= B because two triangular faces never share an edge.

Run: python3 referee_t667_checks4.py
"""
import random
from fractions import Fraction as F
from kobon import verify

random.seed(66741)


def sec(s):
    print()
    print("=" * 74)
    print(s)


def map_line(M, line):
    a, b, c = line
    d = M[0][0] * M[1][1] - M[0][1] * M[1][0]
    Mi = [[F(M[1][1], d), F(-M[0][1], d)], [F(-M[1][0], d), F(M[0][0], d)]]
    return (Mi[0][0] * F(a) + Mi[1][0] * F(b),
            Mi[0][1] * F(a) + Mi[1][1] * F(b), F(c))


R3 = [[0, 1], [-1, -1]]     # order 3,  x^2 + x + 1
R4 = [[0, -1], [1, 0]]      # order 4,  x^2 + 1
R6 = [[1, -1], [1, 0]]      # order 6,  x^2 - x + 1


def bounded_edges(lines):
    tot = 0
    for i in range(len(lines)):
        pts = set()
        for j in range(len(lines)):
            if i == j:
                continue
            p = verify.intersect(lines[i], lines[j])
            if p is not None:
                pts.add(p)
        tot += max(0, len(pts) - 1)
    return tot


def build_orbit(M, m, norb):
    lines, orb = [], {}
    for o in range(norb):
        L = (F(random.randint(-15, 15)), F(random.randint(-15, 15)),
             F(random.randint(-15, 15)))
        for _ in range(m):
            orb[len(lines)] = o
            lines.append(L)
            L = map_line(M, L)
    if len(set(lines)) != m * norb:
        return None, None
    return lines, orb


sec("667(l)  the residue law, measured (parallels allowed -- even m forces them)")
print("   %-5s %-4s %-5s %-24s %s" % ("grp", "k", "T", "predicted", "check"))
for name, M, m in (("C3", R3, 3), ("C4", R4, 4), ("C6", R6, 6)):
    mod = 1 if m == 3 else (m if m % 3 else m // 3)
    for norb in (2, 3, 4):
        for _ in range(200):
            lines, orb = build_orbit(M, m, norb)
            if lines is None:
                continue
            tri = verify.triangles(lines)
            b = sum(1 for (i, j, k, _) in tri
                    if len({orb[i], orb[j], orb[k]}) == 1)
            T = len(tri)
            good = (T % 3 == b % 3) if m == 3 else (T % mod == 0)
            print("   %-5s %-4d %-5d %-24s %s"
                  % (name, m * norb, T,
                     ("T = b (mod 3), b=%d" % b) if m == 3
                     else "T = 0 (mod %d)" % mod,
                     "OK" if good else "*** VIOLATION ***"))
            break

sec("667(n)  Lemma 4 measured: point-symmetric arrangements at k = 14 and 18")
for k in (14, 18):
    print("   k = %d,  target %d" % (k, {14: 54, 18: 94}[k]))
    for f in (0, 2, 4):
        bound = (k - f) * (k - 3) + f * (k - f)
        print("      f=%d centre lines: B <= %d  =>  T <= %d"
              % (f, bound, bound // 3))
    best = 0
    for _ in range(400):
        C0 = (F(random.randint(-3, 3)), F(random.randint(-3, 3)))
        f = random.choice([0, 2, 4])
        lines = []
        for _ in range(f):
            a, b = random.randint(-9, 9), random.randint(-9, 9)
            if (a, b) == (0, 0):
                a = 1
            lines.append((F(a), F(b), F(a) * C0[0] + F(b) * C0[1]))
        while len(lines) < k:
            a, b = random.randint(-9, 9), random.randint(-9, 9)
            if (a, b) == (0, 0):
                a = 1
            c = F(random.randint(-20, 20))
            L = (F(a), F(b), c)
            L2 = (F(a), F(b), 2 * (F(a) * C0[0] + F(b) * C0[1]) - c)
            lines += [L, L2]
        if len(set(lines)) != k:
            continue
        T = verify.count(lines)
        if T > best:
            best = T
            bb = bounded_edges(lines)
    print("      best random point-symmetric sample: T = %d, bounded edges = %d, 3T = %d"
          % (best, bb, 3 * best))
    print("      max of the bound over even f: %d  ->  T <= %d  (best known %d)"
          % (max((k - f) * (k - 3) + f * (k - f) for f in range(0, k + 1, 2)),
             max((k - f) * (k - 3) + f * (k - f) for f in range(0, k + 1, 2)) // 3,
             {14: 53, 18: 93}[k]))

sec("667(o)  rotational symmetry against the three open targets")
for k, tgt in ((14, 54), (18, 94), (20, 117)):
    print("   k = %d, target %d" % (k, tgt))
    survivors = []
    for m in range(2, k + 1):
        # representable? m odd: m | k. m even: k = m*x + (m/2)*y
        if m % 2:
            rep = (k % m == 0)
        else:
            rep = any((k - m * x) >= 0 and (k - m * x) % (m // 2) == 0
                      for x in range(k // m + 1))
        if not rep:
            continue
        reasons = []
        if m == 2 or m % 2 == 0:
            if tgt % 2:
                reasons.append("T even (point reflection in the group)")
            bound = max((k - f) * (k - 3) + f * (k - f)
                        for f in range(0, k + 1, 2))
            if 3 * tgt > bound:
                reasons.append("segment budget B <= %d < 3*%d" % (bound, tgt))
        if m >= 3:
            mod = 1 if m == 3 else (m if m % 3 else m // 3)
            if mod > 1 and tgt % mod:
                reasons.append("T = 0 (mod %d), %d mod %d = %d"
                               % (mod, tgt, mod, tgt % mod))
        if reasons:
            print("      C%-3d EXCLUDED   %s" % (m, "; ".join(reasons)))
        else:
            print("      C%-3d SURVIVES" % m)
            survivors.append(m)
    print("      survivors: %s" % (survivors if survivors else "NONE"))
    print()
print("   Mirror (line-reflection) and dihedral symmetry are a DIFFERENT")
print("   family: a line reflection fixes the axis and every perpendicular,")
print("   and symmetric triangles are genuinely fixed, so none of the above")
print("   applies to it.  Untouched, and unexamined by anyone in 667 turns.")
